using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PZChecklistLibrary
{
    public enum ItemCategory
    {
        Accessory,
        Ammo,
        Animal,
        AnimalPart,
        AnimalPartWeapon,
        Appearance,
        Badger,
        Beaver,
        BrokenWeapon,
        Bug,
        Bunny,
        Camping,
        Cartography,
        Communications,
        Cooking,
        CookingWeapon,
        Corpse,
        Dog,
        Duck,
        Electronics,
        Entertainment,
        Explosives,
        FireSource,
        FirstAid,
        FirstAidWeapon,
        Fishing,
        FishingWeapon,
        Food,
        Fox,
        Frog,
        Furniture,
        Gardening,
        GardeningWeapon,
        Generic,
        Hedgehog,
        Hidden,
        Household,
        HouseholdWeapon,
        Instrument,
        InstrumentWeapon,
        Junk,
        JunkWeapon,
        LightSource,
        Literature,
        Material,
        MaterialWeapon,
        Memento,
        Mole,
        Paint,
        Raccoon,
        Security,
        SkillBook,
        Spider,
        Sports,
        SportsWeapon,
        Squirrel,
        Teddy,
        Tool,
        ToolWeapon,
        Trapping,
        Unknown,
        VehicleMaintenance,
        VehicleMaintenanceWeapon,
        Water,
        WaterContainer,
        Weapon,
        WeaponCrafted,
        WeaponImprovised,
        WeaponPart
    }
}
